#!/usr/bin/env bash

set -euxo pipefail

cd $(dirname $0)/..

if [[ -n "${ENVIRONMENT:-}" ]]; then
    echo "Environment is ${ENVIRONMENT}"
    if [[ "${ENVIRONMENT}" = "DEV" ]]; then
        export GCP_PROJECT_ID="data-services-asia-dev"
        echo "Project ID => ${GCP_PROJECT_ID}"
    elif [[ "${ENVIRONMENT}" = "PROD" ]]; then
        export GCP_PROJECT_ID="dataservices-asia-prod"
        echo "Project ID => ${GCP_PROJECT_ID}"
    else
        echo "Unsupported ENVIRONMENT Value, Exiting!!!"
        exit 1
    fi
else
    echo "ENVIRONMENT Value can't be null, Exiting!!!"
    exit 1
fi

echo "Building the docker image"
IMAGE_NAME=python-app:"${BUILDKITE_BUILD_NUMBER:-latest}"
GCR_IMAGE_URL=asia.gcr.io/"${GCP_PROJECT_ID}"/"${IMAGE_NAME}"

docker build -t "${IMAGE_NAME}" -f Dockerfile .

echo "Tagging the image"
docker tag "${IMAGE_NAME}" "${GCR_IMAGE_URL}"

echo "Pushing the image to Google Container Registry"
docker push "${GCR_IMAGE_URL}"
