#!/usr/bin/env bash

set -euxo pipefail

cd $(dirname $0)/..

echo "Building the docker image"
IMAGE_NAME=python-app:"${BUILDKITE_BUILD_NUMBER:-latest}"

docker build -t "${IMAGE_NAME}" -f Dockerfile .

