apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: {{ .Values.certificate.name }}
spec:
  {{- with .Values.certificate.domains }}
  domains:
    {{- toYaml . | nindent 4 }}
  {{- end }}